you_search_resources_server:
  resources_servers:
    you_search:
      entrypoint: app.py
      domain: agent
      ydc_api_key: ${ydc_api_key}
      search_mode: snippets
      use_judge: true
      judge_model_server:
        type: responses_api_models
        name: judge_model
      judge_responses_create_params:
        input: []
      verified: false
judge_model:
  responses_api_models:
    openai_model:
      entrypoint: app.py
      openai_base_url: ${search_judge_model_base_url}
      openai_api_key: ${search_judge_model_api_key}
      openai_model: ${search_judge_model_name}
you_search_simple_agent:
  responses_api_agents:
    simple_agent:
      entrypoint: app.py
      resources_server:
        type: resources_servers
        name: you_search_resources_server
      model_server:
        type: responses_api_models
        name: policy_model
