name: Community Bot

on:
  issues:
    types: [opened, edited, reopened, closed, deleted]
  issue_comment:
    types: [created, edited, deleted]

jobs:
  community-bot:
    uses: NVIDIA-NeMo/FW-CI-templates/.github/workflows/_community_bot.yml@d48ee21a4986f7281abf746b7d500880c0e91f41 # v1.5.1
    with:
      community_project_id: ${{ vars.COMMUNITY_PROJECT_ID }}
      app-id: ${{ vars.BOT_ID }}
    secrets:
      BOT_KEY: ${{ secrets.BOT_KEY }}
